name: ci pipeline

on:
  push:
    branches:
      - feat/add_dockerfile

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: set short commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      version-tag: ${{ steps.vars.outputs.sha_short }}

  build-and-push-container-image:
    needs: get-version
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: check dockerfile policy
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: dockerfile
          dockerfile_path: .
          check: CKV_DOCKER_7,CKV_DOCKER_8,CKV_DOCKER_10

      - name: push container image to container registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: warapongpj/sample-app:${{ needs.get-version.outputs.version-tag }}
